function [Y,Xf,Af] = trainedNetAnnotation(X,~,~)
%TRAINEDNETANNOTATION neural network simulation function.
%
% Generated by Neural Network Toolbox function genFunction, 13-Nov-2018 00:40:16.
% 
% [Y] = trainedNetAnnotation(X,~,~) takes these arguments:
% 
%   X = 0xTS cell, 0 inputs over TS timesteps
% 
% and returns:
%   Y = 0xTS cell of 0 outputs over TS timesteps.
% 
% where Q is number of samples (or series) and TS is the number of timesteps.

%#ok<*RPMT0>

% ===== NEURAL NETWORK CONSTANTS =====


% ===== SIMULATION ========

% Format Input Arguments
isCellX = iscell(X);
if ~isCellX, X = {X}; end;

% Dimensions
TS = size(X,2); % timesteps

% Allocate Outputs
Y = cell(0,TS);

% Time loop
for ts=1:TS

end

% Final Delay States
Xf = cell(0,0);
Af = cell(0,0);

% Format Output Arguments
if ~isCellX, Y = cell2mat(Y); end
end

% ===== MODULE FUNCTIONS ========

